### ISSUE TITLE
Onion service for The New Oil blog

### ISSUE THREAD

**Issue by vecna13** [tnonate/thenewoil#1]
Thanks for setting up an onion service for The New Oil! Is there a plan to add an onion service for the blog too? I tried http://blog.vyrgfx4jz2lnejqduons56ph5xtsrtaoo7ovny53dd7okyzhfsgkzbad.onion/ but it just serves the regular site.

**Comment by tnonate** [comment]
At this time, no, there is no plan to add additional hidden services. That doesn't mean they're off the table down the road, but it's always important to me that I don't overcommit my time or financial resources, so I prefer to move in baby steps. Right now the website is the main focus, but I can revisit the blog at a later date.
