### ISSUE TITLE
Uptime Monitor TLS

### ISSUE THREAD

**Issue by tnonate** [tnonate/thenewoil#12]
I'm attempting to add an uptime monitor at "https://uptime.thenewoil.org". Right now I have successfully created the unencrypted "http://162.0.238.97:3001/status/thenewoil." I've used [Uptime Kuma](https://github.com/louislam/uptime-kuma) to do so, and I'm attempting to use [this documentation](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#caddy-with-docker-compose) to create TLS with Caddy. I'm not sure what I'm doing wrong. I've copied that template into the Caddyfile at `/etc/caddy/` but I keep getting an error in systemctl that says

`{"level":"info","ts":1711571401.2591567,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized directive: services:
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.`

Not sure what I'm doing wrong.

**Comment by jonaharagon** [comment]
Sounds like you should be using this documentation instead: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#caddy

**Comment by tnonate** [comment]
Am I not using Docker-compose already? I lose track, there's like, 5 different versions of Docker.

Should I simply stick that code in my Caddyfile?

**Comment by tnonate** [comment]
Well damn. That did it. Thanks, man. I appreciate all the time you're taking today to help lol

https://uptime.thenewoil.org/status/thenewoil
