### ISSUE TITLE
Replace uBlock origin with uMatrix

### ISSUE THREAD

**Issue by Bedrovelsen** [tnonate/thenewoil#21]
# Replace uBlock origin with uMatrix 

Suggestion: Use [uMatrix](https://github.com/gorhill/uMatrix) instead of uBlock origin in the Extensions section for
following page https://thenewoil.org/en/guides/most-important/browser/

## Issues with uBlock origin

> uBlock Origin, AdBlock Plus, AdGuard, Disconnect, etc ...
> ... A huge, constantly updated, list of blocked elements is required for these to work ...
> ... when it's so simple to just block entire classes of requests via uMatrix, rendering most of these adblockers irrelevant.

> By using them, you are also relying on someone else to provide you with the lists, instead of taking your web browsing into your own hands. If something isn't on these lists, it will not be blocked, and you cannot possibly make a list that will capture everything ever ... 
> ... So, you are putting the control of your browsing into the hands of a few list maintainers - which, I guess, is still better than the hands of trackers or advertisers. Who incidentally have been ferociously fighting these lists for a long time now (BlockAdBlock, etc.). This has then spawned userscripts and such that block BlockAdBlock, which the advertisers have again responded to ...
> ... uMatrix just sidesteps this whole dumb war. With a properly configured uMatrix, you don't need to care about what tricks the trackers or advertisers have got up their sleeves, since it will all be blocked until you choose otherwise ("default deny" versus "default allow" policy).

[Inferior Privacy Addons](http://digdeeper.club/articles/addons.xhtml#adblockers)

## Justification for uMatrix as a replacement

> Every time you visit any website, you are making a request to it. A website can consist of many files, such as image, style files, or scripts (which can ALSO make their own requests). To complicate matters, it can also make connections to other websites (these are called third-party requests). So, by visiting one website you can end up with hundreds of all types of requests. Now, most privacy issues in the end reduce to a browser making a request with the intention of data collection. The prevention of spying, then, would have to include disabling certain kinds of requests. Okay, but what does uMatrix have to do with all that?
>
> uMatrix divides all requests into eight categories: Cookies, CSS (style files), image, media (audio and video files), scripts, XHR (requests made by scripts), frames (embedding other sites), and other (anything else). And then into another level of other categories: first and third party. What does this mean? Simply, certain types of requests are much more likely to be privacy intruding than others, and uMatrix allows disabling them globally, and then enabling them only on certain websites that you choose.
> 
> The requests most responsible for spying are the third party ones, especially scripts. So let's go and block them all. Now any website that contains a facebook script cannot spy on you anymore - but if you allow first-party scripts, you can still use Facebook - it just can't spy on you elsewhere. Another example - Google's ReCaptcha. You might want to globally allow it - OR, if you don't care about it except you need to access some website just once - allow it only for that website.
> 
> However, tracking prevention is not the only use of uMatrix. Removing clutter ("ads"), annoying popups pestering you to "sign up", video embeds, etc. are all possible. And if you realize you want video embeds on your favorite website, but not elsewhere, you can just allow them there. The best thing about uMatrix is that you can globally block everything with it, and only allow it when and where you need it. It gives you almost complete control over your browsing, and with an intuitive interface too. Of course it will take a while to learn and configure it the way you want to, but for that level of power, it's worth it; and you can go gentle at first - just blocking third-party scripts and cookies will do a lot. Without this addon, that power would be in the hands of trackers and advertisers again - you'd see what and when they want you to see.
 
[Reccomended Privacy Addons - uMatrix](http://digdeeper.club/articles/addons.xhtml#umatrix)

---
---

**uMatrix** - https://github.com/gorhill/uMatrix
**Dig Deeper** - http://digdeeper.club/articles/addons.xhtml

**Comment by tnonate** [comment]
Thank you for your well-thought-out input. Clearly this is something you feel strongly about. I say this as a former uMatrix user and lover: I'm not doing this. Two reasons why. First and foremost: uMatrix is no longer actively maintained. In addition for automatically disqualifying it per our [criteria](https://thenewoil.org/en/criteria/#universal-requirements), that also means with every passing day it becomes more and more likely of a critical security vulnerability existing (if one doesn't already) that won't be patched, putting users at risk. Second, uMatrix is not as user-friendly as uBlock. Thanks again for your concern though.
